from __future__ import annotations

from sqlalchemy.orm import Session

from app.models.tables import Document
from app.portfolio.scoring import parse_portfolio_markdown_table, pick_active_set
from app.skills.registry import register
from app.skills.runner import SkillRunResult, _create_task
from app.util.ids import new_uuid
from app.util.time import now_utc


@register("weekly_review")
def weekly_review(*, db: Session, tenant_id: str, user_id: str | None, inputs: dict) -> SkillRunResult:
    """Portfolio weekly review.

    Inputs:
    - portfolio_doc_id: Document id containing the markdown portfolio table
    - portfolio_markdown: raw markdown content (alternative)
    - min_active (default 3)
    - max_active (default 7)

    Outputs:
    - Document(domain='portfolio', doc_type='weekly_review') summary
    - Tasks for each selected project's next action (if present)
    """

    portfolio_doc_id = (inputs or {}).get("portfolio_doc_id")
    portfolio_md = (inputs or {}).get("portfolio_markdown")

    if portfolio_doc_id and not portfolio_md:
        doc: Document | None = (
            db.query(Document)
            .filter(Document.tenant_id == tenant_id, Document.id == portfolio_doc_id)
            .one_or_none()
        )
        if doc and doc.content_text:
            portfolio_md = doc.content_text

    if not portfolio_md:
        tid = _create_task(db, tenant_id=tenant_id, title="[PORTFOLIO] Provide portfolio_markdown or portfolio_doc_id")
        db.commit()
        return SkillRunResult(
            status="BLOCKED",
            reason="Missing portfolio",
            artifacts={},
            created_task_ids=[tid],
            outbox_ids=[],
            pending_action_ids=[],
            confirmation_tokens={},
        )

    rows = parse_portfolio_markdown_table(portfolio_md)
    if not rows:
        tid = _create_task(db, tenant_id=tenant_id, title="[PORTFOLIO] Portfolio markdown table not found or empty")
        db.commit()
        return SkillRunResult(
            status="BLOCKED",
            reason="Portfolio parse failed",
            artifacts={},
            created_task_ids=[tid],
            outbox_ids=[],
            pending_action_ids=[],
            confirmation_tokens={},
        )

    min_active = int((inputs or {}).get("min_active") or 3)
    max_active = int((inputs or {}).get("max_active") or 7)
    active = pick_active_set(rows, min_n=min_active, max_n=max_active)

    lines = ["# Weekly review", "", "## Active set", ""]
    for i, r in enumerate(active, start=1):
        lines.append(f"{i}. **{r.project}** (score={r.score}, status={r.status})")
        if r.next_action:
            lines.append(f"   - next: {r.next_action}")
    lines.append("")
    lines.append("## Notes")
    lines.append("- Generated by skill weekly_review")
    review_md = "\n".join(lines) + "\n"

    review_doc = Document(
        id=new_uuid(),
        tenant_id=tenant_id,
        workflow_id=None,
        domain="portfolio",
        doc_type="weekly_review",
        title="Weekly review",
        content_text=review_md,
        object_key=None,
        meta={"source_portfolio_doc_id": portfolio_doc_id},
        created_at=now_utc(),
    )
    db.add(review_doc)

    created_tasks: list[str] = []
    for r in active:
        if r.next_action:
            created_tasks.append(
                _create_task(
                    db,
                    tenant_id=tenant_id,
                    title=f"[PORTFOLIO] {r.project}: {r.next_action}",
                    meta={"project": r.project, "area": r.area, "score": r.score},
                )
            )

    db.commit()

    return SkillRunResult(
        status="DONE",
        reason=None,
        artifacts={"weekly_review_doc_id": review_doc.id, "active_count": len(active)},
        created_task_ids=created_tasks,
        outbox_ids=[],
        pending_action_ids=[],
        confirmation_tokens={},
    )
